### ISSUE TITLE
Timing for non-packaged TTML

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#105]
Submitter: Oliver Woodman
Email: olly@google.com
This report refers to the following sentence in the doc:

"If segmented subtitles are needed, such as for live sources, ISOBMFF-packaged TTML or WebVTT segments are expected be used to provide proper timing."

It's unclear to me that there are any limitations preventing "proper timing" in the non-packaged case. The TTML/VTT times in each segment could be defined to be relative to the start of the Period (as is currently the case in the doc) or the start of the Segment. There are no technical limitations preventing "proper timing" under either approach, as far as I can tell.

Could the document be updated to do one of the following:

- If the goal is simply to get everyone using ISOBMFF packaging for this case then I've no objection, but could you please just remove the "to provide proper timing" part of the sentence, since it confuses matters.

- If there is some technical limitation preventing "proper timing" for the non-packaged case, could the doc briefly explain what it is.

- If neither of the above holds, could the document be updated to allow multiple segments of non-packaged TTML/VTT, and clarify whether the TTML/VTT times in each segment should be relative to the start of the period or the start of the segment.

**Comment by TobbeEdgeware** [comment]
For subtitles packaged in ISOBMFF the timing should follow 14496-30.

The only other case I've seen used is to have a side-loaded text file, either TTML and WebVTT. The problem in this case is that there is no standard defining how to relate the timing to the media timeline. However, since this is only for VoD it is natural to assume that the 0 in the TTML timeline is at the start of the VoD media. This is supported in dash.js and other players.

I don't see any reason that we should include multiple non-packaged subtitle segments.

**Comment by TobbeEdgeware** [comment]
Reading this again, I don't really consider it as a bug since "proper timing" is defined in the obvious place, namely ISO/IEC 14496-30:2014 for both WebVTT and TTML in ISOBMFF.

Anyway, to make this clear, let's change the text to:

If segmented subtitles are needed, such as for live sources, ISOBMFF-packaged TTML or WebVTT segments **shall** be used **with timing according to [29]**. **In particular, this means that the TTML timing inside the segments is with respect to the media timeline.**"

instead of

"If segmented subtitles are needed, such as for live sources, ISOBMFF-packaged TTML or WebVTT segments are expected be used to provide proper timing."

The last sentence about the TTML timing offset might be superfluous, and should probably be put in 6.4.4 somewhere, but there is no good place to put it at present.

Note that there seems to be an error in table 21, which refers to ISO/IEC 14496-30 as [32]

**Comment by mikedo** [comment]
Although I agree that the text as drafted could use improvement, I think the proposed "default" is backwards.  That is, I believe ISO BMFF-packaging is required in the general case. I don't believe use of the ISO BMFF-packaged files need further explanation, or if they do, the problem is not clear.

Then, under certain conditions x, y and z, a sidecar file can work. For example, "When the TTML/WebVTT file timing is aligned with a single MPD Period [including offsets, etc], then a "sidecar" file can be used." and/or whatever other special conditions will work.

I believe the text should be constructed in the above manner.

**Comment by haudiobe** [comment]
addressed in v3.33
