### ISSUE TITLE
Edit Lists with Bitstream Switching

### ISSUE THREAD

**Issue by tinskip** [Dash-Industry-Forum/DASH-IF-IOP#168]
Section 6.2.5.2 has various statements indicating that audio and video should not be synchronized by means of Edit List, and that any edit lists present in initialization segments should be ignored.  On the other hand, the CMAF specification states that edit lists shall be used exactly for this purpose (section 1.3.13).

Why this requirement in the IOP, and why only for bitstream-switching streams?  How can it be reconciled with CMAF?  Can we just remove this restriction so that the edit lists are used for sync adjustments, while presentation time offset is used for gross adjustments such as ad insertion?

**Comment by KilroyHughes** [comment]
CMAF constraints the use of edit lists, as noted. DASH IF profiles didn't. 
The question remains whether the @PresentationTimeOffset is before or after applying an offset edit. 

For example, a video CMAF Track File using v1 'trun' and positive composition offsets is encoded with a 4 frame decoded picture buffer removal delay. The earliest decoded sample has decode time zero by ISOFMFF definition. The earliest sample composition time is 4 x sample duration x timescale. An offset edit list is required to subtract presentation time from all sample composition times in all movie fragments to make the earliest sample presentation time equal zero so video will sync with audio and MPD timelines.

In this case, @presentationTimeOffset could either be the composition time or the composition time with the presentation time with the composition delay subtracted by the edit list. In the second case, the offset edit will likely be applied twice because an initialization segment with edit list will be appended to an MSE buffer or other media pipeline and apply that offset in addition to the presentationTimeOffset supplied via API (such as MSE). The file parser and decoder will just process the segments provided … edit list and all. There needs to be agreement between the MPD writer, player, and media pipeline where the composition delay will be subtracted so it will happen once. 

CMAF limits the scope of the problem, but it is a general problem. 

It is more complicated when the earliest segment doesn't start at decode time zero (unconstrained CMAF Track), live streams, streams edited for ad insertion and other purposes, etc. Note that subsampled Representations could use more reference frames with longer removal delay given the codec level used for the Adaptation Set, but that would result in presentation time gaps and overlaps between tracks because all Fragments have the same decode time, but would have different presentation times (CMAF constrains that case). 

Regarding audio edit lists, there are two cases allowed in CMAF. 
1. AAC has a decoder removal delay that hasn't traditionally been represented by a composition delay in ISOBMFF. A second frame must be processed by the encoder and decoder before the first frame can be removed because an overlap transform is used. The timestamp applied can be based on the time of entry or exit. If 'tfdt' decode time matches the intended presentation time, a decoder needs to start decoding slightly in advance to output the sample at the decode time, which also equals its composition time and its presentation time. If encoder delay was included in the timestamp, that should be recorded in an offset edit list to correct the presentation time. Current practice is for many decoder to assume a typical presentation time correction whether or not an edit list is present. CMAF makes it explicit.
2. All audio codecs have sample durations that are normally different from video sample durations and result in audio segments with different durations and start times from video segments. CMAF requires Presentations to start at the start of a video Fragment, but audio Fragments can and will overlap the earlies video sample start time. An audio edit list can be included to explicitly trim the leading audio samples so that audio and video will be start aligned. It is relatively easy to random access a leading audio sample in the Fragment, start decoding, but only output audio in sync with the start of video. This may not be possible at splice points when the first audio Fragment overwrites part of the last audio Fragment in an MSE buffer, so would need to be avoided by splice conditioned re-encoding and packaging.

AFAIK, DASH IF profiles allow both audio and video segments to overlap Period@start, as determined by @presentationTimeOffset. It isn't a problem for the DASH player, it just fails in normal media decoders, i.e. interfaced by MSE. Random start and splice within a video Fragment is much harder due to temporal prediction, frame reordering, etc. that could require decoding several seconds of video in a fraction of that time before starting or resuming presentation.

The splice constraints for seamless playback using a single MSE buffer and decoder are so constraining as to be impractical in many scenarios. The use of multiple buffers and decoders allows gaps and overlaps between segments in sequenced Periods, different codecs and encoding parameters, different delivery methods (e.g. file download combined with live streaming), etc. Multiple video buffers and decoders is a more practical solution for e.g. ad insertion by independent ad networks compared to restricting ad and program segmentation, encoding parameters, download timing, etc. to mimic a single continuous ISOBMFF track (with occasional @PTO change) that can be decoded by a single MSE buffer and decoder without re-initialization. Making continuous program playback more complicated for content preparation and DASH players to allow flexible ad insertion is like using a hammer to pound in screws. An ad insertion app with its own media element, like a screwdriver, is a better tool for that job.

**Comment by kqyang** [comment]
Re https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/168#issuecomment-389847714,

> Edit lists shall not be present in video Adaptation Sets unless they are offered in On-Demand profile.

This does not align with CMAF which allows EditList to be used when there are positive composition offsets.

> If present in any Representation in the Adaptation Set, the edit list shall be identical in all Representations.

This effectively disallows mixing H264 base profile and main profile in the same AdaptationSet as H264 base profile does not support b-frame so composition offsets are always 0, so EditList shall not be used with H264 base profile while EditList could be present per CMAF specification.

**Comment by haudiobe** [comment]
added to v4.2.1
