### ISSUE TITLE
Clarification on mutability of MPD@type

### ISSUE THREAD

**Issue by LloydW93** [Dash-Industry-Forum/DASH-IF-IOP#169]
We've been having conversations with TV manufacturers and our packaging vendor lately about what should happen in an MPD when the end of an event stream is signalled.

Currently an emsg is sent to signal MPD invalidity, at which time the MPD@type attribute is changed to static. The opinion of ourselves and our integration partners is that changing this attribute is incorrect as this is then advertising a new presentation, rather than an update to the existing one.

However, ISO-23009-1 does not specify whether this value is mutable. DASH-IF IOP suggests that when re-using segments to generate pseudo-ondemands that a new MPD should be created, but still the specific wording is unclear.

Should it be considered valid behaviour for an MPD@type attribute to change from "dynamic" to "static" once the live presentation has ended? Can the relevant guidelines be updated to be more specific around this?

**Comment by TobbeEdgeware** [comment]
The IOP 4.1 spec Section 4.6 "Provisioning of Live Content in On-Demand Mode" says that a a new MPD should be generated, but not that the URL should be different. Given that the text goes into some length about how to change the MPD, my interpretation is that you can reuse the same URL, but I agree that it may need to be clarified.

In my view, it is also natural to use an emsg box, as you do, to indicate a new publishTime of the MPD and put that publishTime in the static MPD

**Comment by haudiobe** [comment]
There is no problem. You remove  minUpdatePeriod and add mediaPresentationDuration. type stays dynamic for this case. At some point you can change to static at the same URL or a different one. Will add some text to IOP-

**Comment by TobbeEdgeware** [comment]
To be able to test the player behaviour in this aspect, I've extended the dash-live-source-simulator with the possibility of "start-over" program. The relative times in the URLs are changed into absolute times in a Location element so that the player can repeatedly ask for manifest updates without changing the start and stop time.

https://vm2.dashif.org/livesim-dev/startrel_-60/stoprel_-20/timeoffset_0/testpic_2s/Manifest.mpd

https://vm2.dashif.org/livesim-dev/startrel_-20/stoprel_20/timeoffset_0/testpic_2s/Manifest.mpd

These URLs both point to 40s time slice of a live channel, but the first one is all in the past (-60s, -20s) relative now, while the second is still ongoing (-20s, 20).

The URLs above return DASH MPDs using $Number$, but the corresponding  MPDs with SegmentTimeline are also available:

https://vm2.dashif.org/livesim-dev/segtimeline_1/startrel_-60/stoprel_-20/timeoffset_0/testpic_2s/Manifest.mpd

https://vm2.dashif.org/livesim-dev/segtimeline_1/startrel_-20/stoprel_20/timeoffset_0/testpic_2s/Manifest.mpd

An interesting thing to note is that Shaka-player starts from the beginning of the interval in both the static case and the dynamic case (triggered by mediaPresentationDuration being present in the dynamic case). This is typically the desired behaviour from our customers.

I wrote some more info in https://github.com/Dash-Industry-Forum/dash-live-source-simulator/wiki/Live-channel-and-start-over-of-programs

**Comment by haudiobe** [comment]
addressed in v4.13
