### ISSUE TITLE
Make consistent use of RFC2119 key words

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#175]
The IOP document currently references RFC2119 key words ("SHALL" and similar) in section 2.3 but then immediately deviates from usual RFC2119 practices:

> These key words are attempted to be used consistently in this document, but only in small letters. 

Besides the use of small letters, the entirely of section 2.3.1 is worded in a way that seems to weaken the meaning of these key words to just a suggestive level.

This seems to me counterproductive. First of all, nobody expects it. If you see "shall" and "should" in a technical document, these implicitly have very well known meaning. To deviate from this undermines the value of IOP as it leads to lack of shared understanding. Given that 2.3.2 says these key words are just attempted to be used consistently, none of them can truly be relied upon when talking about whether content conforms to IOP.

DASH has a massive and unmanageable scope. IOP helps a lot to constrain it (though I agree with many who say even IOP contains too much flexibility). We should avoid undermining this cause and make consistent use of key words in their RFC2119 meaning.

Therefore, I propose that from IOP v5 onward, all new or updated content switch to strict usage of RFC2119 key words.

**Comment by haudiobe** [comment]
Proposal to update italics - ask board

2.3.2.	Key Words
The key word usage _is aligned_ with the definitions in _RFC 2119 [44]_, namely:
•	SHALL:   This word means that the definition is an absolute requirement of the specifica-tion.
•	SHALL NOT:   This phrase means that the definition is an absolute prohibition of the specification.
•	SHOULD: This word means that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course. 
•	SHOULD NOT:   This phrase means that there may exist valid reasons in particular cir-cumstances when the particular behavior is acceptable or even useful, but the full implica-tions should be understood and the case carefully weighed before implementing any be-havior described with this label.
•	MAY:   This word means that an item is truly optional.  One vendor may choose to in-clude the item because a particular marketplace requires it or because the vendor feels that it enhances the product while another vendor may omit the same item. 
_These key words are attempted to be used consistently in this document, but only in small letters._

**Comment by sandersaares** [comment]
This got dealt with, I believe. Whatever the case, this issue is out of date with any later discussions, so closing.
