### ISSUE TITLE
Can the first segment of a Representation deviate in duration by more than 50% ?

### ISSUE THREAD

**Issue by nicoweilelemental** [Dash-Industry-Forum/DASH-IF-IOP#191]
Here the use case is mainly multiperiod live DASH with ad replacement, in a pure SegmentTemplate/$Number$ scheme. Assuming that the encoder, when needing to signal the ad break, splits the GOP where the ad break starts, and inserts an IDR frame at the beginning of the 2nd part of the GOP, instead of a B or P frame: it will result at the packager level into two DASH segments with variable lengths.

If the left segment is shorter than 50% compared to the advertised segment size, it is well covered by the 3.2.1 section where we say "Note that the last segment in a Representation may be shorter according to ISO/IEC 23009-1 [4]".

But what is the guideline when the right segment is shorter than 50% compared to the advertised segment size ? Shall we allow it also, with the risk that a short segment at the start of a period delays the moment when the player will request the second segment of the period, being faked by a first segment duration which can be shorter by 90% or more than the expected duration. It actually presents a low risk in a regular streaming use case, where the player has one or more segment in the buffer, but with low latency DASH, we often see situations where the buffer size is inferior to the segment length.

Therefore, unless we have a manifest-level answer to this problem, I would suggest to introduce a player recommendation saying that "At the start of a period, if a segment duration is inferior to 50% compared to the expected duration, the player needs to anticipate the request for the 2nd segment of the period by a corresponding amount of time (0.5xExpectedSegmentDuration-FirstSegmentDuration)".

**Comment by haudiobe** [comment]
Discussion during DASH-IF LIVE TF:
- The problem is understood
- Primarily it is an issue of the packager, but at ad insertion, it does more or less just split the segments
- Simple ways to solve
-- add the @availabilityTimeOffset to indicate the segments are earlier, this may however be confusing when combined with low latency.
-- add a new attribute or supplemental descriptor that provides the duration of the first segment
-- add a new attribute or supplemental descriptor that provides the reduction of the first segment compared to the nominal one (this is a combination of the above two which is least damaging)
I would suggest the latter, but still make this a bug fix/exception that this should only be used if packager cannot solve issue.

**Comment by nicoweilelemental** [comment]
And what about Representation@presentationTimeOffset : could we use that for signaling ?

**Comment by haudiobe** [comment]
Basic Spec text:
- avoid it
- if you do it, you must add the new defined signal
- Client getting this signal should use it to adjust segment availability times by this, 50% is not observed

**Comment by nicoweilelemental** [comment]
We have found a way to avoid it in the encoder upstream of the packager. As the packager cannot control the upstream encoder parameters, it will need to trigger alerts whenever the first segment deviates by more than 50% of the expected duration because of the ingested stream.
