### ISSUE TITLE
Can we allow MPD updates that do more than extend the timeline?

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#224]
IOP v4.3 section 4.4.3.3 says "updates in the MPD only extend the timeline".

I am wondering if we can allow more flexibility here.

Consider a situation where I insert a 3-minute period with pre-generated content (e.g. a very long ad). Having inserted this 3-minute period, the quoted statement in IOP would forbid me to cut it short later and start a new period before the 3-minute periopd ends if I consider it important (maybe someone is about to score a goal in soccer and I don't care about the 3-minute ad so much anymore!).

To enable "cutting short" this 3-minute period I would have to drip-feed segments from it into the dynamic MPD. I suppose this is doable but is it really necessary? It might be possible to just allow MPD updates to overwrite existing parts of the timeline. However, this really depends on what we can reasonably expect non-sophisticated clients to implement.

I raise this topic for discussion so that client authors could comment on whether this should be considered to be in scope of interoperable behavior. What do existing players do if they see that a period that used to be 3 minutes long is now 1 minute long after an MPD update? What if they are alredy 2 minutes into this period? Is this something complex or is it an area where a simple implementation can be expected to be flexible?

@epiclabsDASH @ojw28 I request your view on this.

My practical experiments with MSE based players say overwriting timeline works fine. However, these are very limited experiments.

**Comment by sandersaares** [comment]
Dynamic MPDs are mapped to real time on the service side, so I would expect the 3 minutes to be in the future, beyond the live edge.

Here is my interpretation:

1. The live edge is `t=now`
1. Desired position to play is `t=now-SPD`
1. Neither the live edge or the desired play position changes when more content is added to the end, as scheduling is time relative, not segment list relative.

Does this conflict with your implementation? That is, do you schedule things based on the segment list instead of the mapping to real time?

**Comment by ojw28** [comment]
It probably does conflict with our implementation, although what you describe makes sense. Given your explanation as to how it should work, I think it's probably reasonable that an MPD update can remove and replace content from the end of the presentation. If it were to be allowed, I think some constraints would probably be necessary for sanity. The ones that spring to mind are:

1. A constraint that content can only be removed if it's at least X seconds ahead of `now`. X would probably need to be chosen to be larger than the duration of media pipelines that client players are typically feeding into (so that clients are able to handle such changes without having to flush and re-initialize the underlying pipeline), plus some leeway for clock inaccuracy. I would have thought a fairly small number (e.g. somewhere in the range of 2 - 5) would be sufficient, but that's a guess.
1. A constraint that content cannot be added to a period from which content has been removed. In other words, if you're removing content, you must start a new period to subsequently add content.
1. Well defined rules about how content removal is reflected in the manifest update. I think you'd need to handle the possibility of whole periods being removed for a general solution (e.g. extend your example to inserting N periods corresponding to an ad break containing N ad slots, and consider interrupting that prior to the final ad). So there are open questions about how that's reflected in the manifest (is the period completely removed, or is its duration set to 0, or something else).

**Comment by sandersaares** [comment]
IOP has related section 5.3.3.2.5, although it is not clear to me how this section actually implements this feature.

**Comment by sandersaares** [comment]
There also exist infinite segment sequences:

* SegmentTemplate + duration sequences never end
* SegmentTimeline with `S@r="-1"` is also infinite

Does this statement in IOP, that you can only extend the timeline, mean that you can never stop a period with an infinite segment sequence? I do not think that makes sense. However, there is currently no clear alternative interpretation that surfaces when I read the document.

Some more clear definition seems very much needed here. I am thinking of the following:

1. Services can remove content by reducing period duration and removing periods but NOT by removing existing segment references.
1. Services can remove content after `now+minimumUpdatePeriod`. We should also include a warning that implementation may need to account for MPD update download+processing delay and consider that players may already have buffered some removed data, so the "safe" boundary may be further along (but is implementation-specific).
1. Clients will do whatever they want with data that is already buffered but was removed - playing it is fine; flushing buffers is also fine, even if it is not seamless (if service wants to avoid that, it shouldn't remove so eagerly, after all).

This also captures the "you need to make a new period to continue" rule listed a few comments up because it would ensure that any removal means that the current period ends.

**Comment by sandersaares** [comment]
I agree that thinking of the infinite sequences as self-extending up to `now` is a useful interpretation, though if we use this interpretation in IOP we need to clearly spell it out clearly.

> The alternative expressed in this week's call (by Thomas) was that segments should be drip-fed.

The downside of this is implementation complexity on the service side. While most live services are going to be able to drip-feed main content anyway, as it is produced in real time, I am somewhat concerned that existing implementations might see ad insertion as "external data" and lack the functionality to drip-feed the segments on a fine-grained level. Indeed, the ad insertion solutions I see in practice tend to be extremely simplistic in their implementation, merely doing the minimum to somehow "hook into" the stream and get out of the way as soon as possible.

Thus while a drip-feeding of inserted content is technically workable, I am somewhat concerned that people would not bother implementing it in this way due to the extra work required on the service side. We might say that we consider this the interoperable way but I predict that services would likely do it differently anyway, doing early termination by removing content and then filing bugs against players when things break.

> I don't think the infinite cases you mention are at odds with that approach. If you think of them as I describe then they are drip-feed cases (where the client is doing the drip-feeding as it self-extends the sequence).

I agree. That scenario is probably fairly uncontroversial and largely just a matter of wording things clearly. The main problem comes with non-infinite cases, where you have a SegmentBase or a SegmentTimline with individual segments.

>  If the ad is on-demand profile and you want to cut it short then that might be a compelling use case. Although is it currently permitted to shove an on-demand profile period into the middle of a live stream?

Yes, that is one use case I had in mind. There is a request open to specify how to support exactly that here: https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/182

It is currently scheduled to be tackled in v5 scope. It seems a fairly reasonable thing to want to do, especially if you have ads prepared as on-demand profile content already, so I imagine we will specify whatever is needed to make it OK to do in a nice way.

**Comment by sandersaares** [comment]
I incorporated the removal possibility roughly as described above in #210 but I am open to rolling it back if it seems unnecessary in light of #182 or if the wider audience believes drip-feeding is a realistic expectation.

**Comment by technogeek00** [comment]
Supposing you've served a 3 minute ad pod in place of the original live stream content, I agree with the thought that this is basically the preannouncement of future content. As long as only segments within this future availability time are removed, there should be no direct impact on client buffer as the client should not have attempted the segment requests yet.

@sandersaares your removal update description in #210 directly aligns with all the requirements we outlined internally for early ad termination:
- The last period MAY change from unlimited duration to fixed duration.
- The duration of the last period MAY be shortened.
- One or more periods MAY be removed entirely from the end of the MPD.

For robustness the client must be able to handle the case where it has already downloaded the segment and could possibly be decoding it (we've seen this due to clock drift), but following the playout or removal of the segment from the buffer, the client can resume typical buffer maintenance.

I think the result of #182 is independent of if we add this removal description. As early termination of a vod ad in a live stream is a very practical case, I like the suggestion that we allow MPD updates to remove content at the end and keep the explicit details of possible changes that can occur.

**Comment by sandersaares** [comment]
F2F discussion: yes, go with this as described in #210

**Comment by sandersaares** [comment]
This is incorporated into #210. If there are more comments, please comment in #210.
