### ISSUE TITLE
How can I have xlink periods with flexible duration

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/DASH-IF-IOP#240]
I want the ad server to decide how long the ad should be. I might signal "up to 60s" in the xlink URL but if the ad server wants to make it 5 seconds I am fine with that. I have main content for any timestamp - I want the xlink to overwrite part of the timeline (duration specified by ad server) with an ad, with my xlink period just defining the start point.

So in its base state, I would view this as a 0-duration xlink period, which extends based on ad server response, and skip the equal duration of content from what used to be the continuous period after the ad.

Is this a scenario that can be implemented in an interoperable way? If so, how do I signal it?

There is some text about interrupted periods in IOP 5.3.2.1.1 but I do not understand what this paragraph is trying to say.

**Comment by technogeek00** [comment]
As you are referencing 5.3.2.1.1 I assume the context you are referencing to is Live and what you are attempting is variable length ad replacement instead of fixed? I'm not sure this is possible within the general timing model, but can you confirm I'm understanding the scenario correctly?

**Comment by sandersaares** [comment]
Yes, that's right. I have a marker that says at 12:34:56 today there's a spot for an ad, up to 30 seconds. I want the ad server to have the freedom to decide how long the real ad period might be, between 0 to 30 seconds.

In some sense thisi is possible - the duration of the xlink period can be supplied by the ad server. However, instead of overwriting part of the main content timeline, this would act as an insertion in the MPD, which is not very meaningful.

**Comment by sandersaares** [comment]
I believe this was pushed to ad insertion task force at F2F.

I do not see any obvious mechanism for this. To be clear, "this cannot be done" is a perfectly fine statement to make on this. I am after clarity most of all.

**Comment by technogeek00** [comment]
I would assert that broadly that xlink cannot be used for ad replacement at the live head in dynamic presentations, but I would like to offer my reasoning to see if I am misinterpreting or missing something.

Scenario:
- Live stream with ad break occurring at 150s mark
- Ad break is expected to be 90 seconds
- Ad server decides to only fill 60 seconds via two 30 second ad periods

My general assumptions about the MPD for this scenario:
- `MPD@type="dynamic"`
- The MPD has an appropriate `MPD@availabilityTimeOffset`
- All Periods have a valid `Period@start` value
- MPD contains multiple periods
- Periods are cut on desired insertion boundaries and wherever else necessary for proper signalling
- The stream is otherwise compliant to the IOP described timing model

There are two possible ways of using xlink decoration for the ad break:
- Xlink decoration on an empty period prior to the replaced content (as you stated you want to have the main content for any timestamp)
- Xlink decoration on in-stream ad period that should be replaced

For the empty period with xlink decoration case, you will end up with a period structure like this:

```xml
<MPD ...>
    ...
    <Period start="PT100.0S" id="content-100" duration="PT50.0S"></Period>
    <Period start="PT150.0S" id="ad-remote-150" xlink:href="..." xlink:actuate="onRequest"></Period>
    <Period start="PT150.0S" id="ad-default-150"></Period>
</MPD>
```

Based on the MPD update requirement that only the final period may change in duration, the in-stream ad period would come after the xlink decorated empty period. In building a presentation timeline with this manifest, the `ad-remote-150` and `ad-default-150` periods would occupy the same fixed point in the timeline. In this case the assumption I would make is that the later period cuts the duration of the prior one short, meaning the `ad-remote-150` is effectively eliminated from the timeline even before resolution.

The player could perform the resolution, but I believe the resulting MPD structure has the same problem:

```xml
<MPD ...>
    ...
    <Period start="PT100.0S" id="content-100" duration="PT50.0S" ></Period>
    <Period start="PT150.0S" id="ad-resolved-150" duration="PT30.0S"></Period>
    <Period start="PT180.0S" id="ad-resolved-180" duration="PT30.0S"></Period>
    <Period start="PT150.0S" id="ad-default-150"></Period>
</MPD>
```

Attempting replacement with an empty period just seems to not be interoperable with normal timeline build out.

If you choose the in-stream period decoration case, you would have a period structure like this:

```xml
<MPD ...>
    ...
    <Period start="PT100.0S" id="content-100" duration="PT50.0S"></Period>
    <Period start="PT150.0S" id="ad-default-150" xlink:href="..." xlink:actuate="onRequest"></Period>
</MPD>
```

This is easy to make a presentation timeline from and would still provide you with the default content. When the player resolves the ads you would get the realized ad structure:

```xml
<MPD ...>
    ...
    <Period start="PT100.0S" id="content-100" duration="PT50.0S"></Period>
    <Period start="PT150.0S" id="ad-resolved-150" duration="PT30.0S"></Period>
    <Period start="PT180.0S" id="ad-resolved-180" duration="PT30.0S"></Period>
</MPD>
```

This structure again seems fine, but has removed the default content references completely and raises the question: what happens at the next MPD update?

When the original manifest is pulled again, the MPD is reverted to the original default content ad period with xlink decoration. This is an appropriately consistent update for the main manifest, but inconsistent from the perspective of the player timeline. The player could attempt to automatically re-resolve all previously resolved xlinks, but there is no guaranteed of resolution consistency. To best handle this, the player would need to persist the resolution result and perform the replacement when an MPD update occurs. While I don't think this is the proper behavior and can't find a description of this case scenario anywhere in 23009 or the IOP, I also can't find any text explicitly forbidding this functionality.

Supposing that resolution persistence works, the basic xlink replacement logic would result in a gap in the stream as there is no period representing 210 to 240:

```xml
<MPD ...>
    ...
    <Period start="PT100.0S" id="content-100" duration="PT50.0S"></Period>
    <Period start="PT150.0S" id="ad-resolved-150" duration="PT30.0S"></Period>
    <Period start="PT180.0S" id="ad-resolved-180" duration="PT30.0S"></Period>
    <Period start="PT240.0S" id="content-240"></Period>
</MPD>
```

To address this, we would need to specify some sort of "slicing" mode for xlink, where the resolved content only replaces the amount of default content equal to its duration. With this we could theoretically have the player constructing the missing piece by shifting the start time and duration of the default in-stream content:

```xml
<MPD ...>
    ...
    <Period start="PT100.0S" id="content-100" duration="PT50.0S"></Period>
    <Period start="PT150.0S" id="ad-resolved-150" duration="PT30.0S"></Period>
    <Period start="PT180.0S" id="ad-resolved-180" duration="PT30.0S"></Period>
    <!-- period generated by clamping default content period  -->
    <Period start="PT210.0S" id="ad-default-150" duration="PT30.0S"></Period>
    <Period start="PT240.0S" id="content-240"></Period>
</MPD>
```

This resolution persistence and slicing operations could be possible, but I'm worried about the overall complexity of implementing this all within the player.

The scenarios outlined above and some additional complexities around extraneous period cuts, which I omit for brevity, are the basis of my reasoning against xlink for ad insertion at the live head of a dynamic presentation. If there is anything I've missed or incorrectly assumed please let me know.

Variable duration ad replacement and early ad break termination are two complicated, but real world, use cases for live service offerings. As part of the IOPs ad insertion work we will need to specify methods of handling this, which may result in enhancing xlink to address the above concerns or exploring alternative update mechanisms to present inserted content.

**Comment by sandersaares** [comment]
Thank you for thorough explanation! My question has been answered - what I ask about cannot be done like this - so I will just mark this as closed now.

**Comment by grabya** [comment]
I have the same question as OP but for "static" MPD type.

Can I define a Period in a static MPD that references an AD URL that may be resolved to a 10 second ad or a 20 second ad, etc.    Preferably without player changes.

**Comment by haudiobe** [comment]
Yes, this works for xlink and static MPD. The duration is determined by the returning ad.

 

You do not specify the @mediaPresentationDuration, each Period determines its own duration.

 

Thomas
