### ISSUE TITLE
Client clock synchronization

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#252]
In 

"A client presenting a dynamic MPD SHALL synchronize its local clock according to the UTCTiming elements in the MPD and SHALL emit a warning or error to application developers when clock synchronization fails or UTCTiming elements are not available. A client SHALL NOT assume that clocks are synchronized using some default mechanism."

Why do we need the last sentence? how do you check the conformance?

**Comment by sandersaares** [comment]
The idea here is to require services to explicitly define their time synchronization mechanism/mechanisms.

"Default" sync mechanisms are not interoperable, since different services/clients will have different defaults. Right now there is a problem in the ecosystem that some players like dash.js have "default" time sync sources and people just (wrongly) assume it applies to them without understanding what time sync even means. This should be discouraged.

You check the conformance by, for example, asking the player authors if their player implements this statement. Or looking in the documentation.

**Comment by irajs** [comment]
the last sentence is already satisfied by the first shall statement, correct?

**Comment by sandersaares** [comment]
I agree that this is a valid interpretation. One could say that the second statement is there for added emphasis and does not strictly define any new requirements. Possibly it could be converted to an informative note to make this clear.

**Comment by irajs** [comment]
turning it to a note would be good

**Comment by sandersaares** [comment]
This sentence has been converted to an informative note in #210.
