### ISSUE TITLE
Expired periods- definition and SHALL

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#256]
In 
1.
"Expired periods (i.e. those with no remaining segment references) SHALL be removed."
expired periods are not defined. so are remaining segment references. 

Suggest change it to:

"Expired periods, periods which their end points are before the time shift window SHALL be removed."
2. This is a new SHALL requirement which makes some current services including livesim unconforming. Can we change to SHOULD?

**Comment by sandersaares** [comment]
Changed to "Periods with their end points before the time shift window SHALL be removed." in #210.

I see no reason to change to SHOULD just because some existing services are not compatible. It is fine to have services that are only partially conforming to IOP, especially as in this case it is rather a harmless deviation with probably no negative effects. If services want to follow our recommendations to the letter, they need to start cleaning up expired content (although I imagine they already do, really - even if it was not required before).

I'll mark this as closed but feel free to leave a comment if you feel there is a strong reason not to make it a SHALL - we can discuss in IOP call if it seems important.
