### ISSUE TITLE
MPD ContentProtection element not permitted on Period

### ISSUE THREAD

**Issue by mikedo** [Dash-Industry-Forum/DASH-IF-IOP#298]
[This is an MPEG DASH issue].  Both the spec and the schema do not permit this.  The use case is when the same keys are used for all AdaptationSet's. Enabling this would be an optimization. There is no known history of intentionally not enabling this.  Consider permitting ContentProtection on Period and proposing this to MPEG.

**Comment by sandersaares** [comment]
How relevant is this optimization?

The advantage is deduplication of ContentProtection descriptor (which might include sizable PSSH data). The disadvantage is additional parsing complexity, plus potential backward compatibility issues with older clients that do not consider this possibility.

I propose an alternative: deliver the MPD using gzip compression. I bet this will achieve more gains than manual deduplication of the ContentProtection element, without any client parsing logic changes or potential for divergent implementations.

**Comment by mikedo** [comment]
If DASH clients are that fragile, then following this argument, we can never extend the MPD with anything, ever; and we should reject all future MPD extensions.

The MPD In ATSC is, in fact, always gzip'd. The proposal is not about bit efficiency. It's about support for a data model where all Adaptation Sets use the same keys.

**Comment by sandersaares** [comment]
> If DASH clients are that fragile, then following this argument, we can never extend the MPD with anything, ever; and we should reject all future MPD extensions.

I don't think that quite follows. If version N+1 extends the possible locations of an element then it is logical that clients supporting only version N might not load that element. This is because moving the location of an element is a breaking change that is not backward compatible. Existing clients are not going to look in the new place just because it is now allowed in DASH.

This is a breaking change. Yes, it would be quite sensible for MPEG to reject all future MPD extensions if they include breaking changes (unless there is an extremely potent justification).

> The proposal is not about bit efficiency. It's about support for a data model where all Adaptation Sets use the same keys.

I was going by the statement "Enabling this would be an optimization" but I consider that superseded given the clarification here. Good news! This data model is already supported. You can define the same content protection data under every adaptation set. There is no need to change DASH just to achieve this.

**Comment by mikedo** [comment]
Yes, as with all changes to the MPD, DASH clients conforming to 2nd Ed would not process such an addition properly. But this backwards compatibility argument holds for many updates being made to the MPD in the last year. Events come to mind, which I argued your position at the last MPEG meeting and got it fixed. You've touched on a general design evolution premise that has not really been followed to date. Arguably it should, but then let's step back and apply it to all changes to the MPD. Then I would support your position and withdraw the proposal.

**Comment by jpiesing** [comment]
For what it's worth, I'd expect breaking changes to be masked by a change of the profile URI/URN. If version N+1 allows an element to be somewhere not permitted in version N then I would expect MPDs relying on that element being in that new location to be signalled as requiring profile N+1. Of course this does take the risk that some DASH players don't properly test for the profile but any DASH player author who does that needs to take responsibility for making sure their DASH player is seriously robust.

**Comment by sandersaares** [comment]
> Of course this does take the risk that some DASH players don't properly test for the profile but any DASH player author who does that needs to take responsibility for making sure their DASH player is seriously robust.

Perhaps I miss what you mean by "masked" but in either case, would it not work equally as much?

A profile-aware player would see the unsupported profile and fail to play the content because it is an unsupported profile.

A profile-ignorant player would look for ContentProtection and not find it, thereby failing to play the content.

In either case, we end up with a playback failure and broken backward compatibility.

**Comment by jpiesing** [comment]
> Perhaps I miss what you mean by "masked" but in either case, would it not work equally as much?
> 
> A profile-aware player would see the unsupported profile and fail to play the content because it is an unsupported profile.
> 
> A profile-ignorant player would look for ContentProtection and not find it, thereby failing to play the content.
> 
> In either case, we end up with a playback failure and broken backward compatibility.

If a content provider puts ContentProtection *only* somewhere that existing players won't find then the playback failure is their deliberate decision. If they want backwards compatibility then they also need to put ContentProtection somewhere existing players will find.

A profile-aware player would see the unsupported profile and discard everything not in the scope of a supported profile. It may end up discarding the whole MPD if everything is in the scope of profile N+1 and nothing in the scope of profile N. That has very different failure characteristics and modes than failure to obtain a license.

**Comment by RufaelDev** [comment]
I was wondering, what about audio and timed/text subtitle tracks in the period, would they also be encrypted in case encryption is defined at  the period level ? typically the encryption is applied to the video tracks most of the time, and not so much to audio and timed text, also the schemes 'e.g. cbcs' etc mostly target nal structured video data natively. What would be the default behaviour for these tracks in this proposal ?

**Comment by mikedo** [comment]
As noted above, all AdaptationSets would be encrypted with the same keys, a use case in ATSC and on air today.

However, I think the MPD coding efficiency is overshadowed by the backwards compatibility issue identified by Sander. Currently there is no version signaling short of changing the namespace URI which would be even more disruptive. I withdraw this issue.
