### ISSUE TITLE
Media Segment Duration

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#355]
https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#segment-duration-constraints

There are very clear constraints in v4.3 on this. There are recommendations on almost equal durations, but also to not violate the +- 50%. Please reuse

**Comment by irajs** [comment]
Changed the section to the following:

When using [=simple addressing=], the samples contained in a media segment may cover a different time span on the [=sample timeline=] than what is indicated by the nominal timing in the [=MPD Timeline=]. This deviation is defined as the offset between the edges of the nominal time span (as defined by [=MPD Timeline=]) and the edges of the true time span (as defined by [=sample timeline], and is calculated separately for each edge. 

[[MPEGDASH]] 7.2.1 requires:
The duration deviation must be no more than 50% of the nominal media segment duration and may be in either direction.

This document also recommends:
- [=Media segments=] of a [=representation=] SHOULD be equal in duration. Occasional jitter MAY occur (e.g. due to encoder decisions on GOP size).

Note: [[DVB-DASH]] defines some relevant constraints in section 4.5. Consider obeying these constraints to be compatible with [[DVB-DASH]].

**Comment by sandersaares** [comment]
Further iterated on this to remove the duration jitter avoidance recommendation. It was just a copy-paste from v4.3 and not really important for interoperability - as long as services respect the rules of addressing mode (e.g. the 50%), all is well.

I will close the issue as the substance of the matter was already addressed in August.
