### ISSUE TITLE
5.2.9.2. Availability

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/DASH-IF-IOP#381]
[V5 Call 8/14] 
There is not term like "availability window" defined in MPEG DASH spec. Instead "Segment availability times" is a defined term.

We need to either use "segment availability times"
or
1. mention this is a new term introduced by IOP.
2. define the relationship between above to terms and show how "availability window" is derived from "Segment availability times".

**Comment by irajs** [comment]
Changed the text as the following:

A [=media segment=] is <dfn>available</dfn> when an HTTP request to acquire the [=media segment=] can be started and successfully performed to completion by a client. During playback of a [=dynamic MPD=], new [=media segments=] continuously become [=available=] and stop being [=available=] with the passage of time. [[!MPEGDASH]] defines the <dfn>segment availability times<dfn> of a segment as the duration in wall-clock time in which that segment is available.

An <dfn>availability window</dfn> is a time span on the [=MPD timeline=] that determines which [=media segments=] can be expected to be [=available=]. Each [=representation=] has its own [=availability window=]. Consequently, [=availability window=] at each moment is defined by the union of [=segment availability times=] of all available segments at that moment.

**Comment by sandersaares** [comment]
"Availability window" is an important term and introducing it is not an accident. This term positions availability in a way more suitable for easy understanding by readers.

I believe this matches the August changes by Iraj, where the term is kept but better related to DASH terminology. I am further iterating on the wording right now.

I will close this issue since the August changes already addressed this topic. Comments on any later iterations can be reviewed separately.
