### ISSUE TITLE
Timestamp for TTML and WebVTT

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DASH-IF-IOP#83]
Submitter: Olly
Email: olly@google.com
- In the case of TTML segments without encapsulation (mimeType="application/ttml+xml"), it's unclear whether the begin/end timestamps in each segment of TTML are relative to the start of the segment, or whether they're absolute presentation timestamps. Could the recommendations be updated to clarify this.

- The same is also true for WebVTT.

Thanks!

**Comment by rbouqueau** [comment]
Please read: http://www.gpac-licensing.com/2016/03/21/guidelines-on-how-to-embed-ttml-in-mp4-and-dash/

Any improvement on the github document and examples are appreciated.

**Comment by TobbeEdgeware** [comment]
The question is not about the embedded timeline, but on the case of side-loaded TTML and WebVTT files. I don't see any way of using that type of side-loaded files for dynamic manifests, so it should only apply to static manifests. In such cases, the media timeline typically starts at 0 at the beginning of the period, in which case there should be no issue. As far as I can tell, the unclear part is when there is a presentationTimeOffset that is non-zero. In my opinion, it seems reasonable to strive for media timeline alignment even in that case.

**Comment by TobbeEdgeware** [comment]
Reading the issue a second time, I see that it refers to segments. For segments, the only way defined is to use ISOBMFF containers following MPEG-4 Part 30.  For TTML, there is internal timing in the TTML data that should be aligned with the media timeline provided by the box. For WebVTT, the timing is solely given by the containing ISOBMFF box. The link that @rbouqueau provided is highly relevant for the TTML case.

**Comment by sandersaares** [comment]
I believe the question is for a case where the segments are themselves TTML or WebVTT files, without encapsulation. 14496-30 specifies what to do when you encapsulate in ISOBMFF but nothing specifies what to do without encapsulation.

Sounds like there is room for IOP to say something here - either attach the segment contents to the period start or to the segment start. I do not see any obvious reason to prefer one over the other, really. Are there factors that might make one preferable from the encoding side?

Always using the period start might be more universal, as you can basically just cut a single TTML/WebVTT file into segments and not touch any timestamps inside. Whether this is a realistic production case is debatable but it at least keeps things conceptually straightforward.

**Comment by TobbeEdgeware** [comment]
Below is a proposal for updated text for **6.4.2 Subtitles and Captions**:

Technologies for subtitles are as follows:
•	CEA-708 Digital Television (DTV) Closed Captioning [15] 
•	IMSC1 [62] conformant profiles of TTML, packaged as Segments conforming to MPEG-4, Part 30 [30], including subsets such as:
o	W3C TTML [17] 
o	SMPTE Timed Text [18] (including image-based subtitles and closed captioning) 
o	EBU-TT  [21] 
•	3GPP Timed Text [16] 
•	Web VTT [19] packaged as Segments conforming to MPEG-4, Part 30 [30]
For simple use cases, CEA-608/708 based signaling as defined in section 6.4.3 may be used.
For any other use cases, IMSC1 [62] should be used as defined in section 6.4.4. It is expected that most subset profiles of IMSC1 would be reasonably decodable.
ISOBMFF-packaged TTML and WebVTT Media Segments shall be referenced by Representation elements in MPDs, downloaded, initialized, and synchronized for multimedia presentation the same as audio and video Segments.

Side-loaded TTML or WebVTT subtitles or caption files can be used by some players including dash.js. Such files can be indicated in the manifest like: 

```<Period….> 
<AdaptationSet contentType="text" mimeType="application/ttml+xml” lang="swe">
         <Role schemeIdUri="urn:mpeg:dash:role:2011" value="subtitle"/>
         <Representation id="xml_swe" bandwidth="1000">
             <BaseURL>sub_swe_short.xml</BaseURL>
         </Representation>
      </AdaptationSet>
</Period>
```

Note that there is only one file for the full period, limiting this use case to non-live content. 

Such external files are assumed do have a timeline aligned with the period, so that TTML time 00:00:00.000 corresponds to the start of the Period, even if there is an explicit PresentationTimeOffset specified (on Period level).  

The same applies to side-loaded WebVTT files. In that case, the mimeType is text/vtt.  

If segmented subtitles are needed, such as for live sources, ISOBMFF-packaged TTML or WebVTT segments shall be used to provide proper timing.

**Comment by haudiobe** [comment]
Add that subtitle are always a single Representation per Adaptation Set. No switching logic is defined.

**Comment by mikedo** [comment]
I'm concerned that we are revisiting the fairly recent decision to require ISOBMFF encapsulation. "Sidecar" files were explicitly removed in v3.2 (I think).  Can we please have more time to regroup on this issue?  Please don't accept this CR yet.

**Comment by TobbeEdgeware** [comment]
@mikedo It is true that there is a note in v3.2 (and 3.1) at the end of 6.4.2 saying *DASH playback applications such as Web pages can download TTML or WebVTT text files, initial-ize renderers, and synchronize rendering and composition. This specification does not specify interoperable playback of these “sidecar” subtitle files in combination with a DASH audio visual presentation.*

However, Section 6.4.4 says *... for On-Demand cases, the full file of subtitles may be provided in either ISO BMFF or XML data only* and Table in 6.4.4 lists the mime types for TTML both with and without encapsulation. 

Given that a sidecar non-encapsulated files are quite common, and has support in dash.js and many other players, I think it is better that we give simple guidelines than just leave the case undefined. We could of course add a sentence saying that we recommend the use of encapsulated subtitles even for VoD.

**Comment by mikedo** [comment]
I am not necessarily opposed, but we have flipped on this issue a couple of times now and I would like to address it only one more time and get everyone on the same page. The answer specifically impacts ATSC and DVB, and perhaps others...

**Comment by TobbeEdgeware** [comment]
I think it is fine that DVB-DASH is more restricted than the general DASH-IF IOP document. There is already a number of places in the document outlining that. For this particular area, the is actually a note in Table 19: "

(1) DVB DASH only supports ISO BMFF encapsulated TT, but not XML-based.
